[build]
buildCommand = "cd backend && npm install && npx prisma generate"

[deploy]
startCommand = "npx prisma db push --schema=backend/prisma/schema.prisma && node backend/prisma/seed.js && node backend/src/index.js"
